#! /bin/bash

export FLASK_APP=skf/app.py
#export PYTHONPATH=.:$PYTHONPATH
#For windows use below
export PYTHONPATH=.
export SKF_FLASK_DEBUG=True
export SKF_JWT_SECRET='True'
#export PATH=$PATH:/usr/local/opt/rabbitmq/sbin

while :
do
	case "$(ps x |grep -v grep |grep -c "Python skf")" in

	0)  echo "Restarting skf:"
	    python3 skf/app.py 
	    ;;
	2)  echo "SKF already running"
	    ;;
	esac
done
